# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import grpcs.nlp_pb2 as nlp__pb2


class NlpProcessorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.process_nlp = channel.unary_unary(
        '/NlpProcessor/process_nlp',
        request_serializer=nlp__pb2.idata.SerializeToString,
        response_deserializer=nlp__pb2.odata.FromString,
        )


class NlpProcessorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def process_nlp(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NlpProcessorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'process_nlp': grpc.unary_unary_rpc_method_handler(
          servicer.process_nlp,
          request_deserializer=nlp__pb2.idata.FromString,
          response_serializer=nlp__pb2.odata.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'NlpProcessor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
