# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlp.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nlp.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tnlp.proto\"u\n\x05idata\x12\x0b\n\x03oid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x10\n\x08stemming\x18\x03 \x01(\x08\x12\x16\n\x0enamed_entities\x18\x04 \x01(\x08\x12\x14\n\x0cremove_stops\x18\x05 \x01(\x08\x12\x11\n\tlemmatize\x18\x06 \x01(\x08\"\"\n\x05odata\x12\x0b\n\x03oid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t2/\n\x0cNlpProcessor\x12\x1f\n\x0bprocess_nlp\x12\x06.idata\x1a\x06.odata\"\x00\x62\x06proto3')
)




_IDATA = _descriptor.Descriptor(
  name='idata',
  full_name='idata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oid', full_name='idata.oid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='idata.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stemming', full_name='idata.stemming', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='named_entities', full_name='idata.named_entities', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='remove_stops', full_name='idata.remove_stops', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lemmatize', full_name='idata.lemmatize', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=130,
)


_ODATA = _descriptor.Descriptor(
  name='odata',
  full_name='odata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='oid', full_name='odata.oid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='odata.data', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=166,
)

DESCRIPTOR.message_types_by_name['idata'] = _IDATA
DESCRIPTOR.message_types_by_name['odata'] = _ODATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

idata = _reflection.GeneratedProtocolMessageType('idata', (_message.Message,), dict(
  DESCRIPTOR = _IDATA,
  __module__ = 'nlp_pb2'
  # @@protoc_insertion_point(class_scope:idata)
  ))
_sym_db.RegisterMessage(idata)

odata = _reflection.GeneratedProtocolMessageType('odata', (_message.Message,), dict(
  DESCRIPTOR = _ODATA,
  __module__ = 'nlp_pb2'
  # @@protoc_insertion_point(class_scope:odata)
  ))
_sym_db.RegisterMessage(odata)



_NLPPROCESSOR = _descriptor.ServiceDescriptor(
  name='NlpProcessor',
  full_name='NlpProcessor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=168,
  serialized_end=215,
  methods=[
  _descriptor.MethodDescriptor(
    name='process_nlp',
    full_name='NlpProcessor.process_nlp',
    index=0,
    containing_service=None,
    input_type=_IDATA,
    output_type=_ODATA,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_NLPPROCESSOR)

DESCRIPTOR.services_by_name['NlpProcessor'] = _NLPPROCESSOR

# @@protoc_insertion_point(module_scope)
